name: Tests
on: [push]
jobs:
    Tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: echo "This job's status is ${{ job.status }}."
