name: Tests
on: [push]
jobs:
    Tests:
        runs-on: ubuntu-latest
        env:
            working-directory: ./code/

        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: pwd
            - run: python hw.py
            - run: echo "This job's status is ${{ job.status }}."
