name: Tests
on: [push]
env:
    CODE_DIR: code
jobs:
    Tests:
        env:
            working-directory: ${{ env.CODE_DIR }}
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
            - run: python hw.py
            - run: echo "This job's status is ${{ job.status }}."
